[
    {#can not find
        "hostPID": "false",
        "hostIPC": "false",
        "hostNetwork": "false",
        "runAsUser": "non-zero",
        "readOnlyRootFilesystem": "false",
        "allowPrivilegeEscalation": "false",
        "privileged": "false",
        "runAsNonRoot": "true",
        "privileged_apiGroup": "missing",
        "privileged_resources": "missing",
        "privileged_verbs": "missing",
        "automountServiceAccountToken": "false",
        "resources_limits": "missing",
        "mount_host_system": "missing",
        "docker_sock_volume": "missing",
        "hardcoded_secrets": "missing",
        "hardcoded_secrets_env_ref": "missing",
        "capabilities_add_all": "missing",
        "at_least_two_containers": "present"
    },
    { #attack 11 and 12
        "hostPID": "false",
        "hostIPC": "false",
        "hostNetwork": "false",
        "runAsUser": 0,
        "readOnlyRootFilesystem": "true",
        "allowPrivilegeEscalation": "true",
        "privileged": "false",
        "runAsNonRoot": "false",
        "privileged_apiGroup": "missing",
        "privileged_resources": "present",
        "privileged_verbs": "missing",
        "automountServiceAccountToken": "true",
        "resources_limits": "missing",
        "mount_host_system": "present",
        "docker_sock_volume": "missing",
        "hardcoded_secrets": "present",
        "hardcoded_secrets_env_ref": "missing",
        "capabilities_add_all": "present",
        "at_least_two_containers": "missing"
    },
    { #can not find
        "hostPID": "false",
        "hostIPC": "false",
        "hostNetwork": "false",
        "runAsUser": "non-zero",
        "readOnlyRootFilesystem": "true",
        "allowPrivilegeEscalation": "false",
        "privileged": "true",
        "runAsNonRoot": "false",
        "privileged_apiGroup": "present",
        "privileged_resources": "present",
        "privileged_verbs": "missing",
        "automountServiceAccountToken": "false",
        "resources_limits": "present",
        "mount_host_system": "missing",
        "docker_sock_volume": "present",
        "hardcoded_secrets": "present",
        "hardcoded_secrets_env_ref": "missing",
        "capabilities_add_all": "missing",
        "at_least_two_containers": "missing"
    },
    {#can not find
        "hostPID": "false",
        "hostIPC": "false",
        "hostNetwork": "false",
        "runAsUser": "non-zero",
        "readOnlyRootFilesystem": "true",
        "allowPrivilegeEscalation": "true",
        "privileged": "true",
        "runAsNonRoot": "true",
        "privileged_apiGroup": "missing",
        "privileged_resources": "missing",
        "privileged_verbs": "present",
        "automountServiceAccountToken": "true",
        "resources_limits": "present",
        "mount_host_system": "present",
        "docker_sock_volume": "missing",
        "hardcoded_secrets": "missing",
        "hardcoded_secrets_env_ref": "present",
        "capabilities_add_all": "missing",
        "at_least_two_containers": "present"
    },
    {
        "hostPID": "false",
        "hostIPC": "false",
        "hostNetwork": "false",
        "runAsUser": 0,
        "readOnlyRootFilesystem": "false",
        "allowPrivilegeEscalation": "false",
        "privileged": "false",
        "runAsNonRoot": "false",
        "privileged_apiGroup": "missing",
        "privileged_resources": "missing",
        "privileged_verbs": "present",
        "automountServiceAccountToken": "true",
        "resources_limits": "present",
        "mount_host_system": "present",
        "docker_sock_volume": "missing",
        "hardcoded_secrets": "missing",
        "hardcoded_secrets_env_ref": "missing",
        "capabilities_add_all": "present",
        "at_least_two_containers": "missing"
    }
]